### ISSUE TITLE
2.0.15 - me.host not defined?

### ISSUE THREAD

**Issue by birnbam** [grzegorz914/homebridge-openwebif-tv#11]
Hi,

looks like "me.host" is not defined in /usr/lib/node_modules/homebridge-openwebif-tv/index.js
`this.log('Device: %s, saved channels file successfully.', me.host);`

log:
```
[1/31/2020, 12:11:47 PM] [OpenWebIfTv] result {"services": [{"servicereference": "1:7:1:0:0:0:0:0:0:0:FROM BOUQUET \"userbouquet.robert_hd.tv\" ORDER BY bouquet", "program": 0, "servicename": "Robert HD", "pos": 1}, {"servicereference": "1:7:1:0:0:0:0:0:0:0:FROM BOUQUET \"userbouquet.robert_old.tv\" ORDER BY bouquet", "program": 0, "servicename": "Robert, old", "pos": 2}, {"servicereference": "1:7:1:0:0:0:0:0:0:0:FROM BOUQUET \"userbouquet.iptv.german.tv\" ORDER BY bouquet", "program": 0, "servicename": "IPTV german", "pos": 3}, {"servicereference": "1:7:1:0:0:0:0:0:0:0:FROM BOUQUET \"userbouquet.iptv.german.movies.tv\" ORDER BY bouquet", "program": 0, "servicename": "IPTV movies german", "pos": 4}, {"servicereference": "1:7:1:0:0:0:0:0:0:0:FROM BOUQUET \"userbouquet.sky__tv__1.tv\" ORDER BY bouquet", "program": 0, "servicename": "Sky (TV)", "pos": 5}, {"servicereference": "1:7:1:0:0:0:0:0:0:0:FROM BOUQUET \"userbouquet.IPTV_Channels_List__tv_.tv\" ORDER BY bouquet", "program": 0, "servicename": "IPTV_Channels_List", "pos": 6}, {"servicereference": "1:7:1:0:0:0:0:0:0:0:FROM BOUQUET \"userbouquet.favourites.tv\" ORDER BY bouquet", "program": 0, "servicename": "Favourites (TV)", "pos": 7}, {"servicereference": "1:7:1:0:0:0:0:0:0:0:FROM BOUQUET \"userbouquet.bouquetname__tv_.tv\" ORDER BY bouquet", "program": 0, "servicename": "bouquetname (TV)", "pos": 8}], "pos": 8}
**[1/31/2020, 12:11:47 PM] [OpenWebIfTv] Can not acces device: vu-livingroom.kugler.internal. Might be due to a wrong settings in config, error TypeError: Cannot read property 'host' of undefined
    at openwebifTvDevice.printBouquetsDetail (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:562:64)**
    at /usr/lib/node_modules/homebridge-openwebif-tv/index.js:551:8
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:291:8)
    at JSON.stringify (<anonymous>)
    at openwebifTvDevice.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:285:24)
    at Request._callback (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:309:5)
    at Request.self.callback (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21):
[1/31/2020, 12:11:47 PM] [OpenWebIfTv] error: TypeError: Cannot read property 'host' of undefined
[1/31/2020, 12:11:47 PM] [OpenWebIfTv] -----Device vu-livingroom.kugler.internal-----
[1/31/2020, 12:11:47 PM] [OpenWebIfTv] Manufacturer: Vu+
[1/31/2020, 12:11:47 PM] [OpenWebIfTv] Model: undefined
[1/31/2020, 12:11:47 PM] [OpenWebIfTv] Kernel: 3.14.28
[1/31/2020, 12:11:47 PM] [OpenWebIfTv] Chipset: 7444s
[1/31/2020, 12:11:47 PM] [OpenWebIfTv] Firmware: 2019-10-05-vti-master (5ede501b9)
[1/31/2020, 12:11:47 PM] [OpenWebIfTv] Webif version.: OWIF 1.2.8
[1/31/2020, 12:11:48 PM] [OpenWebIfTv] prepareTvService
[1/31/2020, 12:11:48 PM] [OpenWebIfTv] prepareTvSpeakerService
[1/31/2020, 12:11:48 PM] [OpenWebIfTv] prepareInputServices
[1/31/2020, 12:11:48 PM] [OpenWebIfTv] publishExternalAccessories for device: vu-livingroom.kugler.internal
[1/31/2020, 12:11:48 PM] Fernseher is running on port 34891.
[1/31/2020, 12:11:48 PM] Please add [Fernseher] manually in Home app. Setup Code: 000-00-000
[1/31/2020, 12:11:49 PM] [OpenWebIfTv] didFinishLaunching
```

config:
```
  "platforms": [
    {
      "platform": "OpenWebIfTv",
      "checkStateInterval": 5,
      "devices": [{
        "name": "Fernseher",
        "host": "vu-livingroom.kugler.internal",
        "port": 80,
        "auth": false,
        "switchInfoMenu": true,
        "bouquets": [
          {
            "name": "gotv neu",
            "reference": "1:0:16:3404:3ED:1:C00000:0:0:0:"
          }
          ]
        }
      ]
    }
  ]
```

**Comment by grzegorz914** [comment]
all fixed in 2.0.16

**Comment by birnbam** [comment]
This one is fixed, but still having problems when using in Scenes.

The log tells me:
```
[1/31/2020, 5:27:04 PM] [OpenWebIfTv] result {"message": "Active service is now '1:0:1:4E27:43A:1:C00000:0:0:0:'", "result": true}
[1/31/2020, 5:27:04 PM] [OpenWebIfTv] Device: vu-livingroom.kugler.internal, set Channel succesed 1:0:1:4E27:43A:1:C00000:0:0:0::
```

but sat-receiver starts with last used channel instead of switching to 1:0:1:4E27:43A:1:C00000:0:0:0::

manually switching channels within the app works without any problems

full log during activating the scene:
```
[1/31/2020, 5:27:04 PM] [OpenWebIfTv] result {"inStandby": "true", "currservice_begin": "", "muted": true, "isRecording": "false", "currservice_description": "", "volume": 100, "currservice_fulldescription": "N/A", "currservice_name": "N/A", "currservice_filename": "", "transcoding": true, "currservice_end": "", "currservice_id": -1}
[1/31/2020, 5:27:04 PM] [OpenWebIfTv] Device: vu-livingroom.kugler.internal, get Power succeded: STANDBY
[1/31/2020, 5:27:04 PM] [OpenWebIfTv] result {"message": "Active service is now '1:0:1:4E27:43A:1:C00000:0:0:0:'", "result": true}
[1/31/2020, 5:27:04 PM] [OpenWebIfTv] Device: vu-livingroom.kugler.internal, set Channel succesed 1:0:1:4E27:43A:1:C00000:0:0:0::
[1/31/2020, 5:27:04 PM] [OpenWebIfTv] result {"instandby": true, "result": true}
[1/31/2020, 5:27:04 PM] [OpenWebIfTv] Device: vu-livingroom.kugler.internal, set Power succeded: ON

```


Best regards
birnbam

**Comment by grzegorz914** [comment]
The last used channel is stored in Enigma 2 settings, this had nothing to do with this plugin.
For correct work U need first start The receiver and after this Switch channel. Can U detalied describe how U Create The start scene?

**Comment by birnbam** [comment]
Home
- Add scene
- custom
-add accessories
Now choose "Fernseher" (which is the openwebif-tv)
- Done
- Press and hold to ajust accessories for this scene
Now long press on "Fernseher"
Now select ON
Now select "Puls 4 Austria"
- Name the scene (e.g. "Test")
- done

All set now.

-Watching e.g. ORF
-Turn off "Fernseher" with app
- Activating scene "Test"
- Fernseher starts with ORF, but app logo says "Fernseher PULS 4 Austria"

Do you need screenshots?
Best regards
birnbam

**Comment by grzegorz914** [comment]
Ok, it is normal bechawiour, as long as U do not switch the channel after power on, the receiver will always start with last saved channel. 
I will look to make some workaround for this.

**Comment by birnbam** [comment]
As I am in a SCENE and I have selected:

- Power on
- channel "PULS4 TV"

I thought this will be done exact in the this sequence - first turn on receiver, second switch channel

If there is a other way to configure please guide me...

Nevertheless, waiting for your workaround...
Best regards
birnbam

**Comment by grzegorz914** [comment]
Test please v.2.0.17 it should be fixed

**Comment by birnbam** [comment]
2.0.17 - still no success.

App reports receiver on, channel PULS4TV (as defined in SCENE) but receiver cam up with old channel instead of switching to requested one.

log:
```
[2/1/2020, 12:17:06 PM] [OpenWebIfTv] result {"instandby": true, "result": true}
[2/1/2020, 12:17:06 PM] [OpenWebIfTv] Device: vu-livingroom.kugler.internal, set new Power state succeded: ON
[2/1/2020, 12:17:06 PM] [OpenWebIfTv] Get data from device: vu-livingroom.kugler.internal, successful
```

**Comment by grzegorz914** [comment]
strange, i have tested on my tuners and all working as excepted. Have U restart homebridge after update?

**Comment by grzegorz914** [comment]
strange, i have tested on my tuners and all working as excepted. Have U restart homebridge after update?

**Comment by birnbam** [comment]
Yes. Currently I'm running homebridge in foreground process instead of service.
```
/usr/lib
├── homebridge@0.4.50
├── homebridge-openwebif-tv@2.0.17
└── npm@6.13.7
```
But during startup I see following error, maybe this is related:
log:
```
[2/1/2020, 12:39:18 PM] Homebridge is running on port 51827.
[2/1/2020, 12:39:18 PM] [OpenWebIfTv] Get data from device: vu-livingroom.kugler.internal, successful
[2/1/2020, 12:39:18 PM] [OpenWebIfTv] -----Device vu-livingroom.kugler.internal-----
[2/1/2020, 12:39:18 PM] [OpenWebIfTv] Manufacturer: Vu+
[2/1/2020, 12:39:18 PM] [OpenWebIfTv] Model: undefined
[2/1/2020, 12:39:18 PM] [OpenWebIfTv] Kernel: 3.14.28
[2/1/2020, 12:39:18 PM] [OpenWebIfTv] Chipset: 7444s
[2/1/2020, 12:39:18 PM] [OpenWebIfTv] Webif version.: OWIF 1.2.8
[2/1/2020, 12:39:18 PM] [OpenWebIfTv] Firmware: 2019-10-05-vti-master (5ede501b9)
[2/1/2020, 12:39:18 PM] [OpenWebIfTv] error: TypeError: Cannot read property 'servicename' of undefined
    at /usr/lib/node_modules/homebridge-openwebif-tv/index.js:568:25
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:281:8)
    at JSON.stringify (<anonymous>)
    at openwebifTvDevice.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:275:24)
    at Request._callback (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:301:5)
    at Request.self.callback (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

```

**Comment by grzegorz914** [comment]
Hm, since ver.2.0.15 this error is fixed. I don’t get this error anymore. I’m not at home right now, I will check this maybe some old file was published to npm. Please remove completely the plugin and install again from scratch.

**Comment by birnbam** [comment]
Removed and re-installed from scratch. The error-message is still there...

**Comment by grzegorz914** [comment]
I have publish 2.0.18 again to npm, tested many times with different channels and all scenes working as excepted. Please test and report again.

**Comment by birnbam** [comment]
Upgraded to 2.0.18 (uninstall previous/ install 2.0.18).
I have good and bad news:

The good news:
switching channels when used in SCENES is working fine!
log:
```
[2/1/2020, 6:07:05 PM] [OpenWebIfTv] Device: vu-livingroom.kugler.internal, set new Power state succeded: ON
[2/1/2020, 6:07:05 PM] [OpenWebIfTv] Get data from device: vu-livingroom.kugler.internal, successful
[2/1/2020, 6:07:05 PM] [OpenWebIfTv] Device: vu-livingroom.kugler.internal, set new Channel succesed 1:0:1:4E27:43A:1:C00000:0:0:0::
[2/1/2020, 6:07:05 PM] [OpenWebIfTv] Get data from device: vu-livingroom.kugler.internal, successful
```

The bad news:
during startup  I receive following error:
log:
```
[2/1/2020, 6:05:28 PM] Loading 1 platforms...
[2/1/2020, 6:05:28 PM] [OpenWebIfTv] Initializing OpenWebIfTv platform...
[2/1/2020, 6:05:28 PM] [OpenWebIfTv] Channels for device: vu-livingroom.kugler.internal, will be created and saved in /home/robert/.openwebifTv/
Load homebridge-switches.AutomationSwitches
[2/1/2020, 6:05:28 PM] Homebridge is running on port 51827.
[2/1/2020, 6:05:28 PM] [OpenWebIfTv] error: ReferenceError: me is not defined
    at /usr/lib/node_modules/homebridge-openwebif-tv/index.js:577:5
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:282:8)
    at JSON.stringify (<anonymous>)
    at openwebifTvDevice.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:276:24)
    at Request._callback (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:301:5)
    at Request.self.callback (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[2/1/2020, 6:05:28 PM] [OpenWebIfTv] Get data from device: vu-livingroom.kugler.internal, successful
[2/1/2020, 6:05:28 PM] [OpenWebIfTv] -----Device vu-livingroom.kugler.internal-----
[2/1/2020, 6:05:28 PM] [OpenWebIfTv] Manufacturer: Vu+
[2/1/2020, 6:05:28 PM] [OpenWebIfTv] Model: undefined
[2/1/2020, 6:05:28 PM] [OpenWebIfTv] Kernel: 3.14.28
[2/1/2020, 6:05:28 PM] [OpenWebIfTv] Chipset: 7444s
[2/1/2020, 6:05:28 PM] [OpenWebIfTv] Webif version.: OWIF 1.2.8
[2/1/2020, 6:05:28 PM] [OpenWebIfTv] Firmware: 2019-10-05-vti-master (5ede501b9)
[2/1/2020, 6:05:29 PM] Fernseher is running on port 34471.
[2/1/2020, 6:05:29 PM] Please add [Fernseher] manually in Home app. Setup Code: 000-00-000
```

**Comment by grzegorz914** [comment]
Sorry for that,, v2.0.19 is ready

**Comment by birnbam** [comment]
2.0.19 - the error message has changed...

log:
```
[2/1/2020, 6:29:04 PM] [OpenWebIfTv] -----Device vu-livingroom.kugler.internal-----
[2/1/2020, 6:29:04 PM] [OpenWebIfTv] Manufacturer: Vu+
[2/1/2020, 6:29:04 PM] [OpenWebIfTv] Model: undefined
[2/1/2020, 6:29:04 PM] [OpenWebIfTv] Kernel: 3.14.28
[2/1/2020, 6:29:04 PM] [OpenWebIfTv] Chipset: 7444s
[2/1/2020, 6:29:04 PM] [OpenWebIfTv] Webif version.: OWIF 1.2.8
[2/1/2020, 6:29:04 PM] [OpenWebIfTv] Firmware: 2019-10-05-vti-master (5ede501b9)
[2/1/2020, 6:29:04 PM] [OpenWebIfTv] Get data from device: vu-livingroom.kugler.internal, successful
[2/1/2020, 6:29:04 PM] [OpenWebIfTv] error: TypeError: Cannot read property 'servicename' of undefined
    at /usr/lib/node_modules/homebridge-openwebif-tv/index.js:603:25
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:282:8)
    at JSON.stringify (<anonymous>)
    at openwebifTvDevice.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:276:24)
    at Request._callback (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:301:5)
    at Request.self.callback (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[2/1/2020, 6:29:04 PM] [OpenWebIfTv] Get data from device: vu-livingroom.kugler.internal, successful
[2/1/2020, 6:29:05 PM] Fernseher is running on port 36731.
```

**Comment by birnbam** [comment]
forgot to mention: 2.0.19 broke SCENE support, old cahnnel instead of requested on( this was ok in 2.0.18)

**Comment by grzegorz914** [comment]
V2.0.20 ready

**Comment by birnbam** [comment]
V2.0.20 installed,
SCENES working again OK

still following error in the log:
```
[2/1/2020, 7:55:17 PM] [OpenWebIfTv] error: TypeError: Cannot read property 'servicename' of undefined
    at /usr/lib/node_modules/homebridge-openwebif-tv/index.js:603:25
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:282:8)
    at JSON.stringify (<anonymous>)
    at openwebifTvDevice.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:276:24)
    at Request._callback (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:301:5)
    at Request.self.callback (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[2/1/2020, 7:55:17 PM] [OpenWebIfTv] Get data from device: vu-livingroom.kugler.internal, successful
[2/1/2020, 7:55:18 PM] Fernseher is running on port 39555.
```

**Comment by grzegorz914** [comment]
Ok,
u can ignore this error, this error appears only at first Run if channel file create.

**Comment by birnbam** [comment]
OK, will continue testing...

BTW: There is **NO** file written to **.openwebifTv**. This directory has been created, but no files in there. Is this OK?

**Comment by grzegorz914** [comment]
No, its not OK, The file must be there, are U sure homebridge have permission to write in this folder?

**Comment by grzegorz914** [comment]
Please set host as IP adres and test, not use FQDN.

**Comment by birnbam** [comment]
Using IP instead of FQDN did not help...

Yes, I'm sure homebridge got permission, just double-checked this.
homebridge is running with **root** so got permission.

Furthermore I did following test:

- deleted **.openwebifTv** folder
-  restarted **homebridge**
- folder **.openwebifTv** has been created (but no files in this directory)

**Comment by grzegorz914** [comment]
Hmm, be me are always created for every receiver:
Any think in log?

![486B724C-0796-4A22-83C0-56E964E616EC](https://user-images.githubusercontent.com/28867813/73598176-0ce2e100-4535-11ea-96fa-3f66a2c5ba99.png)

**Comment by birnbam** [comment]
Hm, I'm running on Ubuntu Linux - maybe this important for you to know...

This I can see in the log:
`[2/1/2020, 8:48:49 PM] [OpenWebIfTv] Channels for device: 10.10.0.223, will be created and saved in /home/robert/.openwebifTv/`

This folder will be created each time I restart homebridge, but no files are created (in very early version there was a file created, but can't remember the verison number)
