### ISSUE TITLE
2.1.10 --> TypeError: Cannot read property 'connectionStatus' of undefined

### ISSUE THREAD

**Issue by birnbam** [grzegorz914/homebridge-openwebif-tv#12]
Hi,
upgraded to 2.1.10, now Homebridge crashes (please see log below)...

best regards
birnbam

log:
```
[2/10/2020, 6:43:19 AM] [OpenWebIfTv] Initializing OpenWebIfTv platform...
[2/10/2020, 6:43:19 AM] TypeError: Cannot read property 'connectionStatus' of undefined
    at openwebIfTvDevice.getBouquets (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:557:11)
    at new openwebIfTvDevice (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:92:9)
    at new openwebIfTvPlatform (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:33:28)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:337:32)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
[2/10/2020, 6:43:19 AM] Got SIGTERM, shutting down Homebridge...
```

**Comment by grzegorz914** [comment]
Sorry for that mistake, fixed in 2.1.11
