### ISSUE TITLE
2.2.42 homebridge crashes

### ISSUE THREAD

**Issue by birnbam** [grzegorz914/homebridge-openwebif-tv#17]
when starting homebridge it crashes during startup.

log:

```
[2/22/2020, 12:45:16 PM] SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:378:22)
    at Request.self.callback (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2/22/2020, 12:45:16 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by grzegorz914** [comment]
Please update to latest version.2.2.48
