### ISSUE TITLE
Homebridge crashes while switching channel

### ISSUE THREAD

**Issue by birnbam** [grzegorz914/homebridge-openwebif-tv#2]
Hi,
When trying to switch channel  homebridge crashes. Any Ideas what I'm doing wrong?

nodejs: v12.14.1
npm: 6.13.4
homebridge@0.4.50
homebridge-openwebif-tv@1.2.11

from the log:
`[1/9/2020, 4:06:10 PM] [Fernseher] Initializing OpenWebIfTv accessory...
[1/9/2020, 4:06:10 PM] [Fernseher] Adding Information Service...
[1/9/2020, 4:06:10 PM] [Fernseher] Adding Television Service...
[1/9/2020, 4:06:10 PM] [Fernseher] Adding Remote Key Service...
[1/9/2020, 4:06:10 PM] [Fernseher] Adding Input Service...kabel eins
[1/9/2020, 4:06:10 PM] [Fernseher] Adding Speaker Service...

[1/9/2020, 4:06:10 PM] Homebridge is running on port 51827.
[1/9/2020, 4:10:09 PM] [Fernseher] getChannel() succeded: undefined
[1/9/2020, 4:10:09 PM] [Fernseher] getPowerState() succeded: OFF
[1/9/2020, 4:10:23 PM] [Fernseher] getPowerState() succeded: OFF
[1/9/2020, 4:10:23 PM] [Fernseher] setPowerState() succeded ON
[1/9/2020, 4:10:28 PM] [Fernseher] new channel: kabel eins
[1/9/2020, 4:10:28 PM] ReferenceError: inputReference is not defined
    at OpenWebIfTvAccessory.setChannel (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:371:46)
    at Characteristic.ActiveIdentifier.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:50:9)
    at Characteristic.ActiveIdentifier.emit (events.js:223:5)
    at Characteristic.ActiveIdentifier.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:223:5)
    at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:223:5)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[1/9/2020, 4:10:28 PM] Got SIGTERM, shutting down Homebridge...`

best regards
birnbam

**Comment by grzegorz914** [comment]
fixed in v.1.2.12
