### ISSUE TITLE
"create channels file" fails

### ISSUE THREAD

**Issue by birnbam** [grzegorz914/homebridge-openwebif-tv#20]
Hi,
upgraded to latest version2.3.19 and still have the problem that the channels file is not written.

Now I had a look at your code, added one debug line, and saw that the piece of code which should write the file is never executed (write permission is granted, since the directory is successfully created).
Can you please have a look?
best regards
birnbam67

here is the log (you can see the line "birnbam: something went wrong...):
```
sudo homebridge -D | grep -i openwebiftv
[3/4/2020, 4:26:39 PM] Registering platform 'homebridge-openwebif-tv.OpenWebIfTv'
[3/4/2020, 4:26:39 PM] [OpenWebIfTv] Initializing OpenWebIfTv platform...
[3/4/2020, 4:26:39 PM] [OpenWebIfTv] birnbam: something went wrong in getBouquets()...
[3/4/2020, 4:26:39 PM] [OpenWebIfTv] Device: 10.10.0.223, will create channels file in: /home/robert/.openwebifTv/
[3/4/2020, 4:26:41 PM] [OpenWebIfTv] prepareTvService
[3/4/2020, 4:26:41 PM] [OpenWebIfTv] prepareTvSpeakerService
[3/4/2020, 4:26:41 PM] [OpenWebIfTv] prepareInputServices
[3/4/2020, 4:26:41 PM] [OpenWebIfTv] Device: 10.10.0.223, channels file does not exist
[3/4/2020, 4:26:41 PM] [OpenWebIfTv] Device: 10.10.0.223, publishExternalAccessories: Fernseher
[3/4/2020, 4:26:42 PM] [OpenWebIfTv] didFinishLaunching
[3/4/2020, 4:26:44 PM] [OpenWebIfTv] Device: 10.10.0.223, name: Fernseher, state: Online
[3/4/2020, 4:26:45 PM] [OpenWebIfTv] -------- Fernseher --------
[3/4/2020, 4:26:45 PM] [OpenWebIfTv] Manufacturer: Vu+
[3/4/2020, 4:26:45 PM] [OpenWebIfTv] Model: undefined
[3/4/2020, 4:26:45 PM] [OpenWebIfTv] Kernel: 3.14.28
[3/4/2020, 4:26:45 PM] [OpenWebIfTv] Chipset: 7444s
[3/4/2020, 4:26:45 PM] [OpenWebIfTv] Webif version.: OWIF 1.2.8
[3/4/2020, 4:26:45 PM] [OpenWebIfTv] Firmware: 2020-02-25-vti-master (216bc5d2a)
[3/4/2020, 4:26:45 PM] [OpenWebIfTv] ----------------------------------
```

here is your piece of code with one line added:
```
       getBouquets() {
                var me = this;
                if (!me.connectionStatus) {
                        me.log.debug('birnbam: something went wrong in getBouquets()...');
                        return;
                } else {
                        request(me.url + '/api/getservices', function (error, response, data) {
                                if (error) {
                                } else {
                                        var json = JSON.parse(data);
                                        var bouquetsList = json.services;
                                        var arrayLength = bouquetsList.length;
                                        for (var i = 0; i < arrayLength; i++) {
                                        }
                                        me.log.debug('Bouquets list', bouquetsList);
                                        me.saveBouquetsChannels(bouquetsList, new Array());
                                }
                        });
                }
        }
```

**Comment by grzegorz914** [comment]
fixed

**Comment by birnbam** [comment]
Now got a new error... and homebridge crashes...

```
sudo homebridge -D | grep -i openwebiftv
[3/4/2020, 8:22:49 PM] Registering platform 'homebridge-openwebif-tv.OpenWebIfTv'
[3/4/2020, 8:22:49 PM] [OpenWebIfTv] Initializing OpenWebIfTv platform...
[3/4/2020, 8:22:50 PM] [OpenWebIfTv] prepareTvService
[3/4/2020, 8:22:50 PM] [OpenWebIfTv] prepareTvSpeakerService
[3/4/2020, 8:22:50 PM] [OpenWebIfTv] prepareInputServices
[3/4/2020, 8:22:50 PM] [OpenWebIfTv] Device: 10.10.0.223, channels file does not exist
[3/4/2020, 8:22:50 PM] [OpenWebIfTv] Device: 10.10.0.223, publishExternalAccessories: Fernseher
[3/4/2020, 8:22:51 PM] [OpenWebIfTv] didFinishLaunching
[3/4/2020, 8:22:52 PM] [OpenWebIfTv] Device: 10.10.0.223, get current Power state successfull: ON
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Device: 10.10.0.223, name: Fernseher, state: Online
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Bouquets list [
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'gotv neu', reference: '1:0:16:3404:3ED:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'ORF1 HD', reference: '1:0:19:132F:3EF:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'ORF2N HD', reference: '1:0:19:1334:3EF:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'ORF III HD', reference: '1:0:19:33FC:3ED:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file {
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'ATV HD', reference: '1:0:19:33AC:3EB:1:C00000:0:0:0::ATV HD' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'ATV2', reference: '1:0:1:33A7:3EB:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'ProSieben HD', reference: '1:0:19:EF75:3F9:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'Pro7 MAXX HD', reference: '1:0:19:EF78:3F9:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'SAT.1 HD', reference: '1:0:19:EF74:3F9:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'VOX HD', reference: '1:0:19:EF11:421:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'RTL HD', reference: '1:0:19:EF10:421:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'NITRO HD', reference: '1:0:19:2EAF:411:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'RTLplus', reference: '1:0:1:2F30:441:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'RTLII HD', reference: '1:0:19:EF15:421:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'SUPER RTL HD', reference: '1:0:19:2E9B:411:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'PULS 4 Austria', reference: '1:0:1:4E27:43A:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file {
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'kabel eins HD', reference: '1:0:19:EF76:3F9:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file {
...
...
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'SYFY HD', reference: '1:0:19:7E:C:85:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'TNT Comedy HD', reference: '1:0:19:88:B:85:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'TNT Film HD', reference: '1:0:19:8C:4:85:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'TNT Serie HD', reference: '1:0:19:7B:9:85:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'Universal TV HD', reference: '1:0:19:65:9:85:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Prepare channels to save in file { name: 'TOGGO plus', reference: '1:0:1:2EFE:441:1:C00000:0:0:0:' }
[3/4/2020, 8:22:54 PM] TypeError: Cannot read property 'servicename' of undefined
    at Request._callback (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:556:25)
    at Request.self.callback (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:311:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] -------- Fernseher --------
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Manufacturer: Vu+
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Model: undefined
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Kernel: 3.14.28
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Chipset: 7444s
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Webif version.: OWIF 1.2.8
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] Firmware: 2020-02-25-vti-master (216bc5d2a)
[3/4/2020, 8:22:54 PM] [OpenWebIfTv] ----------------------------------
[3/4/2020, 8:22:59 PM] [OpenWebIfTv] Device: 10.10.0.223, get current Power state successfull: ON
```

**Comment by grzegorz914** [comment]
update and check again

**Comment by birnbam** [comment]
Cool, thanks - now it's working :)

log:
```
[3/4/2020, 8:52:28 PM] [OpenWebIfTv] Device: 10.10.0.223, saved channels successfull in /home/robert/.openwebifTv/:
[3/4/2020, 8:52:29 PM] [OpenWebIfTv] -------- Fernseher --------
[3/4/2020, 8:52:29 PM] [OpenWebIfTv] Manufacturer: Vu+
[3/4/2020, 8:52:29 PM] [OpenWebIfTv] Model: undefined
[3/4/2020, 8:52:29 PM] [OpenWebIfTv] Kernel: 3.14.28
[3/4/2020, 8:52:29 PM] [OpenWebIfTv] Chipset: 7444s
[3/4/2020, 8:52:29 PM] [OpenWebIfTv] Webif version.: OWIF 1.2.8
[3/4/2020, 8:52:29 PM] [OpenWebIfTv] Firmware: 2020-02-25-vti-master (216bc5d2a)
[3/4/2020, 8:52:29 PM] [OpenWebIfTv] ----------------------------------
^C
robert@birnbam105:~$ sudo service homebridge restart
robert@birnbam105:~$ ll .openwebifTv/
total 20
drwxr-xr-x  2 root   root   4096 Mar  4 20:52 ./
drwxr-xr-x 22 robert robert 4096 Mar  4 18:40 ../
-rw-r--r--  1 root   root   8196 Mar  4 20:52 channels_10100223
```
