### ISSUE TITLE
hombridge docker

### ISSUE THREAD

**Issue by steini72** [grzegorz914/homebridge-openwebif-tv#32]
ReferenceError: arrayLength is not defined
    at Request._callback (/homebridge/node_modules/homebridge-openwebif-tv/index.js:638:25)
    at Request.self.callback (/homebridge/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by grzegorz914** [comment]
Check 2.6.12, I think is fixed now.

**Comment by grzegorz914** [comment]
I think the problem is solved, close this.
