### ISSUE TITLE
2.6.40 crashes my hombridge

### ISSUE THREAD

**Issue by birnbam** [grzegorz914/homebridge-openwebif-tv#34]
Hi,
just upgraded, now homebridge crashes...

any idea?

log:
````
[5/5/2020, 11:06:51 AM] [OpenWebIfTv] Device: 10.10.0.223 Fernseher, get current Power state successful: ON
[5/5/2020, 11:06:51 AM] [OpenWebIfTv] Device: 10.10.0.223 Fernseher, get current Channel successful: OE3 1:0:2:334D:45B:1:C00000:0:0:0::OE3
[5/5/2020, 11:06:51 AM] [OpenWebIfTv] Device: 10.10.0.223 Fernseher, get current Mute state: OFF
[5/5/2020, 11:06:51 AM] ReferenceError: name is not defined
    at Request._callback (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:217:73)
    at Request.self.callback (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[5/5/2020, 11:06:51 AM] Got SIGTERM, shutting down Homebridge...
[5/5/2020, 11:06:54 AM] [OpenWebIfTv] Device: 10.10.0.223 Fernseher, get current Mute state: OFF
[5/5/2020, 11:06:54 AM] ReferenceError: name is not defined
    at Request._callback (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:217:73)
    at Request.self.callback (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by birnbam** [comment]
upgrade to 2.6.45 fixed this issue for me.
Thx and close
