### ISSUE TITLE
With the new version i get an error and the vu cant be found

### ISSUE THREAD

**Issue by MasterofKungfu9999** [grzegorz914/homebridge-openwebif-tv#45]
21.2.2021, 21:08:43 [OpenWebIfTv] -------- VU --------
21.2.2021, 21:08:43 [OpenWebIfTv] Manufacturer: Vu+
21.2.2021, 21:08:43 [OpenWebIfTv] Model: Uno 4K
21.2.2021, 21:08:43 [OpenWebIfTv] Kernel: 3.14.28
21.2.2021, 21:08:43 [OpenWebIfTv] Chipset: 7252s
21.2.2021, 21:08:43 [OpenWebIfTv] Webif version: OWIF 1.2.8
21.2.2021, 21:08:43 [OpenWebIfTv] Firmware: 14.0.6
21.2.2021, 21:08:43 [OpenWebIfTv] ----------------------------------
21.2.2021, 21:08:43 [OpenWebIfTv] Device: 192.168.13.40 VU, update Device state error: TypeError: this.televisionService.getCharacteristic(...).onGet is not a function
    at openwebIfTvDevice.prepareAccessory (/home/hoobs/.hoobs/node_modules/homebridge-openwebif-tv/index.js:274:5)
    at openwebIfTvDevice.updateDeviceState (/home/hoobs/.hoobs/node_modules/homebridge-openwebif-tv/index.js:232:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5), state: Offline

**Comment by grzegorz914** [comment]
Versin 3.6.0 and abowe need to be used with Homebridge min. v1.3.x

**Comment by MasterofKungfu9999** [comment]
Oh okay. Thanks for your Support
