### ISSUE TITLE
Broken Automation with latest Versions 3.7.36

### ISSUE THREAD

**Issue by BorussiaPlayer17** [grzegorz914/homebridge-openwebif-tv#47]
Using nodejs 15.12 and npm 7.7.4.

Same Problem as the last time. My Automation turns on my Sony TV when my recievier is turned on. But when switching the enigma on, it switches immediately off again and on and off. Goes a bit crazy :D

This brakes my automation. The last Version that works for me is 3.7.25

Greetings.

**Comment by grzegorz914** [comment]
Try 3.7.37

**Comment by BorussiaPlayer17** [comment]
Works again! Thank you! 🙂

**Comment by BorussiaPlayer17** [comment]
Since i Update nodejs to 15.13 my problems are back again. Also with your Version 3.7.37. So i think something changed in node. The TV is constantly turning on an off again. Would be nice if you could check on that. 

Greets

**Comment by grzegorz914** [comment]
latest version is 3.7.56

**Comment by BorussiaPlayer17** [comment]
I know. Even with the latest Version the Enigma goes crazy.

**Comment by grzegorz914** [comment]
all is tested on two box Formula F4 and Ultimo 4K openATV 6.4 and 6.5 all working correct, may be enable debug mode  and get the log.

**Comment by grzegorz914** [comment]
only node 10, 12, 14, 16 are supported

**Comment by BorussiaPlayer17** [comment]
Thats what the log shows:

`[5.4.2021, 11:49:00] [OpenWebIfTv] Device: 192.168.99.10 Receiver, requesting Device state.
[5.4.2021, 11:49:00] [OpenWebIfTv] Device: 192.168.99.10 Receiver, debug response: {
  inStandby: 'true',
  currservice_begin: '',
  muted: true,
  isRecording: 'false',
  currservice_description: '',
  volume: 100,
  currservice_fulldescription: 'N/A',
  currservice_name: 'N/A',
  currservice_filename: '',
  transcoding: true,
  currservice_end: '',
  currservice_id: -1
}
[5.4.2021, 11:49:04] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Power state successful: ON
[5.4.2021, 11:49:04] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Power state successful: OFF
[5.4.2021, 11:49:04] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Channel successful: undefined undefined
[5.4.2021, 11:49:04] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Event successful: N/A
[5.4.2021, 11:49:04] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Power state successful: ON
[5.4.2021, 11:49:04] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Channel successful: 5 Sat.1 HD 1:0:19:CF6F:213:270F:FFFF0000:0:0:0:
[5.4.2021, 11:49:05] [OpenWebIfTv] Device: 192.168.99.10 Receiver, requesting Device state.
[5.4.2021, 11:49:05] [OpenWebIfTv] Device: 192.168.99.10 Receiver, debug response: {
  inStandby: 'false',
  currservice_begin: '11:10',
  currservice_begin_timestamp: 1617613800,
  currservice_end_timestamp: 1617619800,
  muted: false,
  isRecording: 'false',
  currservice_station: 'SAT.1 HD',
  currservice_serviceref: '1:0:19:CF6F:213:270F:FFFF0000:0:0:0:',
  currservice_description: 'Der Storch bringt schon lange keine Babys? Störche liefern Pakete für den weltweiten Online-Handel cornerstore.com.',
  volume: 100,
  currservice_fulldescription: 'Störche  Abenteuer im Anflug\n11:10 - 12:50\n\n',
  currservice_name: 'Störche  Abenteuer im Anflug',
  currservice_filename: '',
  transcoding: true,
  currservice_end: '12:50',
  currservice_id: 4117
}
[5.4.2021, 11:49:07] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Power state successful: ON
[5.4.2021, 11:49:08] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Power state successful: OFF
[5.4.2021, 11:49:08] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Power state successful: ON
[5.4.2021, 11:49:08] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Channel successful: SAT.1 HD 1:0:19:CF6F:213:270F:FFFF0000:0:0:0:
[5.4.2021, 11:49:08] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Event successful: Störche  Abenteuer im Anflug
[5.4.2021, 11:49:09] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Power state successful: ON
[5.4.2021, 11:49:09] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Channel successful: 5 Sat.1 HD 1:0:19:CF6F:213:270F:FFFF0000:0:0:0:
[5.4.2021, 11:49:09] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Power state successful: ON
[5.4.2021, 11:49:09] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Power state successful: OFF
[5.4.2021, 11:49:10] [OpenWebIfTv] Device: 192.168.99.10 Receiver, requesting Device state.
[5.4.2021, 11:49:10] [OpenWebIfTv] Device: 192.168.99.10 Receiver, debug response: {
  inStandby: 'true',
  currservice_begin: '',
  muted: true,
  isRecording: 'false',
  currservice_description: '',
  volume: 100,
  currservice_fulldescription: 'N/A',
  currservice_name: 'N/A',
  currservice_filename: '',
  transcoding: true,
  currservice_end: '',
  currservice_id: -1
}
[5.4.2021, 11:49:13] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Power state successful: OFF
[5.4.2021, 11:49:13] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Channel successful: undefined undefined
[5.4.2021, 11:49:13] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Event successful: N/A
[5.4.2021, 11:49:14] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Power state successful: ON
[5.4.2021, 11:49:14] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Channel successful: 5 Sat.1 HD 1:0:19:CF6F:213:270F:FFFF0000:0:0:0:
[5.4.2021, 11:49:15] [OpenWebIfTv] Device: 192.168.99.10 Receiver, requesting Device state.
[5.4.2021, 11:49:15] [OpenWebIfTv] Device: 192.168.99.10 Receiver, debug response: {
  inStandby: 'false',
  currservice_begin: '11:10',
  currservice_begin_timestamp: 1617613800,
  currservice_end_timestamp: 1617619800,
  muted: false,
  isRecording: 'false',
  currservice_station: 'SAT.1 HD',
  currservice_serviceref: '1:0:19:CF6F:213:270F:FFFF0000:0:0:0:',
  currservice_description: 'Der Storch bringt schon lange keine Babys? Störche liefern Pakete für den weltweiten Online-Handel cornerstore.com.',
  volume: 100,
  currservice_fulldescription: 'Störche  Abenteuer im Anflug\n11:10 - 12:50\n\n',
  currservice_name: 'Störche  Abenteuer im Anflug',
  currservice_filename: '',
  transcoding: true,
  currservice_end: '12:50',
  currservice_id: 4117
}
[5.4.2021, 11:49:15] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Channel successful: 5 Sat.1 HD 1:0:19:CF6F:213:270F:FFFF0000:0:0:0:
[5.4.2021, 11:49:18] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Power state successful: ON
[5.4.2021, 11:49:18] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Power state successful: OFF
[5.4.2021, 11:49:19] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Power state successful: ON
[5.4.2021, 11:49:19] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Channel successful: SAT.1 HD 1:0:19:CF6F:213:270F:FFFF0000:0:0:0:
[5.4.2021, 11:49:19] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Event successful: Störche  Abenteuer im Anflug
[5.4.2021, 11:49:20] [OpenWebIfTv] Device: 192.168.99.10 Receiver, requesting Device state.
[5.4.2021, 11:49:20] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Power state successful: ON
[5.4.2021, 11:49:20] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Channel successful: 5 Sat.1 HD 1:0:19:CF6F:213:270F:FFFF0000:0:0:0:
[5.4.2021, 11:49:20] [OpenWebIfTv] Device: 192.168.99.10 Receiver, debug response: {
  inStandby: 'false',
  currservice_begin: '11:10',
  currservice_begin_timestamp: 1617613800,
  currservice_end_timestamp: 1617619800,
  muted: false,
  isRecording: 'false',
  currservice_station: 'SAT.1 HD',
  currservice_serviceref: '1:0:19:CF6F:213:270F:FFFF0000:0:0:0:',
  currservice_description: 'Der Storch bringt schon lange keine Babys? Störche liefern Pakete für den weltweiten Online-Handel cornerstore.com.',
  volume: 100,
  currservice_fulldescription: 'Störche  Abenteuer im Anflug\n11:10 - 12:50\n\n',
  currservice_name: 'Störche  Abenteuer im Anflug',
  currservice_filename: '',
  transcoding: true,
  currservice_end: '12:50',
  currservice_id: 4117
}
[5.4.2021, 11:49:25] [OpenWebIfTv] Device: 192.168.99.10 Receiver, requesting Device state.
[5.4.2021, 11:49:25] [OpenWebIfTv] Device: 192.168.99.10 Receiver, debug response: {
  inStandby: 'false',
  currservice_begin: '11:10',
  currservice_begin_timestamp: 1617613800,
  currservice_end_timestamp: 1617619800,
  muted: false,
  isRecording: 'false',
  currservice_station: 'SAT.1 HD',
  currservice_serviceref: '1:0:19:CF6F:213:270F:FFFF0000:0:0:0:',
  currservice_description: 'Der Storch bringt schon lange keine Babys? Störche liefern Pakete für den weltweiten Online-Handel cornerstore.com.',
  volume: 100,
  currservice_fulldescription: 'Störche  Abenteuer im Anflug\n' +
    '11:10 - 12:50\n' +
    '\n' +
    'Störche bringen die Babys...zumindest war das früher so. Heute sind sie Paketzusteller eines weltweit operierenden Mega-Online-Versands. Storch Junior zeigt in der Versandabteilung die besten Leistungen und hofft bereits auf eine Beförderung, als er aus Versehen die Babymaschine in Gang setzt, was zur Produktion eines völlig unautorisierten, wenn auch entzückenden Mädchens führt. Junior und sein Freund Tulip, der einzige Mensch auf dem Storchenberg, müssen das Säuglingsbündel nun so schnell wie möglich loswerden, damit der Chef nichts mitbekommt. Hektisch bemühen sie sich also, ihr erstes Baby überhaupt zuzustellen  was in einen wilden und aufschlussreichen Trip mündet, der mehr als eine Familienkrise kitten könnte. Und vielleicht finden die Störche dadurch sogar wieder zurück zu der Mission, für die sie schon immer vorherbestimmt waren.\n' +
    '\n' +
    'Cameraman: Simon Dunsdon\n' +
    'Director: Nicholas Stoller\n' +
    'Director: Doug Sweetland\n' +
    'Composer: Jeff Danna\n' +
    'Composer: Mychael Danna',
  currservice_name: 'Störche  Abenteuer im Anflug',
  currservice_filename: '',
  transcoding: true,
  currservice_end: '12:50',
  currservice_id: 4117
}
[5.4.2021, 11:49:25] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Power state successful: ON
[5.4.2021, 11:49:25] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Power state successful: OFF
[5.4.2021, 11:49:27] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Power state successful: ON
[5.4.2021, 11:49:27] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Channel successful: SAT.1 HD 1:0:19:CF6F:213:270F:FFFF0000:0:0:0:
[5.4.2021, 11:49:27] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Event successful: Störche  Abenteuer im Anflug
[5.4.2021, 11:49:27] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Power state successful: ON
[5.4.2021, 11:49:27] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Channel successful: 5 Sat.1 HD 1:0:19:CF6F:213:270F:FFFF0000:0:0:0:
[5.4.2021, 11:49:30] [homebridge-bravia] Error: 
    at Accessory.sendCharacteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1874:14)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1581:14)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
[5.4.2021, 11:49:30] [OpenWebIfTv] Device: 192.168.99.10 Receiver, requesting Device state.
[5.4.2021, 11:49:30] [OpenWebIfTv] Device: 192.168.99.10 Receiver, debug response: {
  inStandby: 'false',
  currservice_begin: '11:10',
  currservice_begin_timestamp: 1617613800,
  currservice_end_timestamp: 1617619800,
  muted: false,
  isRecording: 'false',
  currservice_station: 'SAT.1 HD',
  currservice_serviceref: '1:0:19:CF6F:213:270F:FFFF0000:0:0:0:',
  currservice_description: 'Der Storch bringt schon lange keine Babys? Störche liefern Pakete für den weltweiten Online-Handel cornerstore.com.',
  volume: 100,
  currservice_fulldescription: 'Störche  Abenteuer im Anflug\n' +
    '11:10 - 12:50\n' +
    '\n' +
    'Störche bringen die Babys...zumindest war das früher so. Heute sind sie Paketzusteller eines weltweit operierenden Mega-Online-Versands. Storch Junior zeigt in der Versandabteilung die besten Leistungen und hofft bereits auf eine Beförderung, als er aus Versehen die Babymaschine in Gang setzt, was zur Produktion eines völlig unautorisierten, wenn auch entzückenden Mädchens führt. Junior und sein Freund Tulip, der einzige Mensch auf dem Storchenberg, müssen das Säuglingsbündel nun so schnell wie möglich loswerden, damit der Chef nichts mitbekommt. Hektisch bemühen sie sich also, ihr erstes Baby überhaupt zuzustellen  was in einen wilden und aufschlussreichen Trip mündet, der mehr als eine Familienkrise kitten könnte. Und vielleicht finden die Störche dadurch sogar wieder zurück zu der Mission, für die sie schon immer vorherbestimmt waren.\n' +
    '\n' +
    'Cameraman: Simon Dunsdon\n' +
    'Director: Nicholas Stoller\n' +
    'Director: Doug Sweetland\n' +
    'Composer: Jeff Danna\n' +
    'Composer: Mychael Danna',
  currservice_name: 'Störche  Abenteuer im Anflug',
  currservice_filename: '',
  transcoding: true,
  currservice_end: '12:50',
  currservice_id: 4117
}
[5.4.2021, 11:49:31] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Power state successful: ON
[5.4.2021, 11:49:31] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Power state successful: OFF
[5.4.2021, 11:49:32] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Power state successful: ON
[5.4.2021, 11:49:32] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Channel successful: SAT.1 HD 1:0:19:CF6F:213:270F:FFFF0000:0:0:0:
[5.4.2021, 11:49:32] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Event successful: Störche  Abenteuer im Anflug
[5.4.2021, 11:49:33] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Power state successful: ON
[5.4.2021, 11:49:33] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Channel successful: 5 Sat.1 HD 1:0:19:CF6F:213:270F:FFFF0000:0:0:0:
[5.4.2021, 11:49:33] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Power state successful: ON
[5.4.2021, 11:49:33] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Power state successful: OFF
[5.4.2021, 11:49:33] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Power state successful: ON
[5.4.2021, 11:49:33] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Channel successful: SAT.1 HD 1:0:19:CF6F:213:270F:FFFF0000:0:0:0:
[5.4.2021, 11:49:33] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Event successful: Störche  Abenteuer im Anflug
[5.4.2021, 11:49:34] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Power state successful: ON
[5.4.2021, 11:49:34] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Channel successful: 5 Sat.1 HD 1:0:19:CF6F:213:270F:FFFF0000:0:0:0:
[5.4.2021, 11:49:35] [OpenWebIfTv] Device: 192.168.99.10 Receiver, requesting Device state.
[5.4.2021, 11:49:35] [OpenWebIfTv] Device: 192.168.99.10 Receiver, debug response: {
  inStandby: 'false',
  currservice_begin: '11:10',
  currservice_begin_timestamp: 1617613800,
  currservice_end_timestamp: 1617619800,
  muted: false,
  isRecording: 'false',
  currservice_station: 'SAT.1 HD',
  currservice_serviceref: '1:0:19:CF6F:213:270F:FFFF0000:0:0:0:',
  currservice_description: 'Der Storch bringt schon lange keine Babys? Störche liefern Pakete für den weltweiten Online-Handel cornerstore.com.',
  volume: 100,
  currservice_fulldescription: 'Störche  Abenteuer im Anflug\n11:10 - 12:50\n\n',
  currservice_name: 'Störche  Abenteuer im Anflug',
  currservice_filename: '',
  transcoding: true,
  currservice_end: '12:50',
  currservice_id: 4117
}
[5.4.2021, 11:49:39] [OpenWebIfTv] Device: 192.168.99.10 Receiver, get current Power state successful: ON
[5.4.2021, 11:49:39] [OpenWebIfTv] Device: 192.168.99.10 Receiver, set new Power state successful: OFF
[5.4.2021, 11:49:40] [OpenWebIfTv] Device: 192.168.99.10 Receiver, requesting Device state.
[5.4.2021, 11:49:40] [OpenWebIfTv] Device: 192.168.99.10 Receiver, debug response: {
  inStandby: 'true',
  currservice_begin: '',
  muted: true,
  isRecording: 'false',
  currservice_description: '',
  volume: 100,
  currservice_fulldescription: 'N/A',
  currservice_name: 'N/A',
  currservice_filename: '',
  transcoding: true,
  currservice_end: '',
  currservice_id: -1
}
[5.4.2021, 11:49:45] [OpenWebIfTv] Device: 192.168.99.10 Receiver, requesting Device state.
[5.4.2021, 11:49:45] [OpenWebIfTv] Device: 192.168.99.10 Receiver, debug response: {
  inStandby: 'true',
  currservice_begin: '',
  muted: true,
  isRecording: 'false',
  currservice_description: '',
  volume: 100,
  currservice_fulldescription: 'N/A',
  currservice_name: 'N/A',
  currservice_filename: '',
  transcoding: true,
  currservice_end: '',
  currservice_id: -1
}
[5.4.2021, 11:49:50] [OpenWebIfTv] Device: 192.168.99.10 Receiver, requesting Device state.
[5.4.2021, 11:49:50] [OpenWebIfTv] Device: 192.168.99.10 Receiver, debug response: {
  inStandby: 'true',
  currservice_begin: '',
  muted: true,
  isRecording: 'false',
  currservice_description: '',
  volume: 100,
  currservice_fulldescription: 'N/A',
  currservice_name: 'N/A',
  currservice_filename: '',
  transcoding: true,
  currservice_end: '',
  currservice_id: -1
}`

**Comment by grzegorz914** [comment]
You get some error from Your Bravia TV, are U using HDMI CEC?

**Comment by BorussiaPlayer17** [comment]
No CEC is deactivated. The tv is got enabled by Homekit automation when the openwebif receiver is turned on. And thats the Problem. The Receiver keeps turning on and off on it's own.

**Comment by grzegorz914** [comment]
your automation logic must be wrong because set the receiver power off direct after power on, can You get the automation logic here?

**Comment by BorussiaPlayer17** [comment]
Very Basic. Receiver turns on and the automation turns on the tv. Nothing more. Even if i turn of the automation the receiver goes crazy. Trying to downgrade my node Version to 14. Will report in a minute.

**Comment by grzegorz914** [comment]
try update to.57 and get feedback

**Comment by BorussiaPlayer17** [comment]
Works better then before. 

I deactiveded two automation and it works. So i Think it was not really your problem. Sorry for that. Will make more test this week. Closing the issue. Thank you for your Help!

Wesołych Świąt
