### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by DocUltra** [grzegorz914/homebridge-openwebif-tv#50]
Hi ,

I get an error 

device info error: Error: ENOENT: no such file or directory, open '/homebridge/openwebifTv/devInfo_1921681055

Do you know what it could be?

**Comment by DocUltra** [comment]
I´ve created the folder manually, now I got a new error

:16:23 PM] Error: ENOENT: no such file or directory, open '/homebridge/openwebifTv/inputs_1921681055'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at openwebIfTvDevice.prepareAccessory (/homebridge/node_modules/homebridge-openwebif-tv/index.js:569:28)
    at OPENWEBIF.<anonymous> (/homebridge/node_modules/homebridge-openwebif-tv/index.js:176:11)
    at OPENWEBIF.emit (node:events:390:28)
    at OPENWEBIF.getDeviceInfo (/homebridge/node_modules/homebridge-openwebif-tv/src/openwebif.js:61:18)
