### ISSUE TITLE
Homebridge crashes with 1.3.4

### ISSUE THREAD

**Issue by birnbam** [grzegorz914/homebridge-openwebif-tv#7]
Hi,
my configuration worked fine with 1.3.0, but after upgrading to 1.3.4 homebridge crashes.
best regards
birnbam

**sniplet from config:**
        "bouquets": [
          {
            "name": "ORF1 HD",
            "reference": "1:0:19:132F:3EF:1:C00000:0:0:0:"
          }
          ]

**homebridge.log:**
[1/13/2020, 7:00:58 AM] [Fernseher] Initializing OpenWebIfTv accessory...
[1/13/2020, 7:00:58 AM] [Fernseher] Adding Information Service...
[1/13/2020, 7:00:58 AM] [Fernseher] Adding Television Service...
[1/13/2020, 7:00:58 AM] [Fernseher] Adding Remote Key Service...
[1/13/2020, 7:00:58 AM] Error: ENOENT: no such file or directory, open '/home/robert/.openwebif/Fernseher/bouquets.json'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at OpenWebIfTvAccessory.generateInputServices (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:129:17)
    at OpenWebIfTvAccessory.getServices (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:176:28)
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:427:36)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:309:26)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
[1/13/2020, 7:00:58 AM] Got SIGTERM, shutting down Homebridge...

**Comment by grzegorz914** [comment]
Fixed in 1.3.5
