### ISSUE TITLE
Homebridge crashes with 1.3.5 when used as service

### ISSUE THREAD

**Issue by birnbam** [grzegorz914/homebridge-openwebif-tv#8]
Hi,
currently I have following situation. After upgrading to 1.3.5:

- homebridge crashes when run as service: "service homebridge-01 start"
- homebridge runs without problems when run as foreground task: "homebridge -U ~/.homebridge-01"

previous version 1.3.0 runs well as service and as foreground task...

Best regards 
birnbam

homebridge-01.log:
[1/14/2020, 6:39:17 AM] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at join (path.js:1039:7)
    at module.exports (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/persist-path/index.js:19:22)
    at new OpenWebIfTvAccessory (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:31:32)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:308:29)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11

**Comment by grzegorz914** [comment]
all fixed, please update to the latest version 2.0.7, need to make changes in config and add again to the HomeKit due to moved to platform and register as external accessory.
In this case RC is always available.
